# Generated by Django 5.0.2 on 2024-03-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_historicalcustomgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'default_permissions': (), 'permissions': [('view_group', 'Can view group'), ('change_group', 'Can change group'), ('delete_group', 'Can delete group'), ('add_group', 'Can add group'), ('change_permissions_group', 'Can change permissions group'), ('view_permissions_group', 'Can view permissions group')], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
