# Generated by Django 5.0.2 on 2024-02-27 10:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconfig', '0003_alter_globalconfig_address_alter_globalconfig_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGlobalConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Georut', max_length=100, null=True, verbose_name='Nombre de la app')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo de la app')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador para documentos')),
                ('name_documents', models.CharField(max_length=100, verbose_name='Nombre para documentos')),
                ('logo_documents', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo para documentos')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección para documentos')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono para documentos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para documentos')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web para documentos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical global config',
                'verbose_name_plural': 'historical global configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
