# Generated by Django 5.0.2 on 2024-02-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalconfig', '0004_historicalglobalconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'default_permissions': (), 'permissions': [('view_global_conf', 'Can view global conf'), ('change_global_conf', 'Can change global conf'), ('delete_global_confr', 'Can delete global conf'), ('add_global_conf', 'Can add global conf')], 'verbose_name': 'Global config', 'verbose_name_plural': 'Global Configs'},
        ),
        migrations.AlterModelOptions(
            name='historicalglobalconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Global config', 'verbose_name_plural': 'historical Global Configs'},
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo de la compañia para mostrar en la app'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='logo_documents',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='name',
            field=models.CharField(blank=True, default='Georut', max_length=100, null=True, verbose_name='Nombre de la compañia para mostrar en la app'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='name_documents',
            field=models.CharField(max_length=100, verbose_name='Nombre de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador de la compañia'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo de la compañia para mostrar en la app'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='logo_documents',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='name',
            field=models.CharField(blank=True, default='Georut', max_length=100, null=True, verbose_name='Nombre de la compañia para mostrar en la app'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='name_documents',
            field=models.CharField(max_length=100, verbose_name='Nombre de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificador de la compañia'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la compañia para mostrar en los documentos'),
        ),
        migrations.AlterField(
            model_name='historicalglobalconfig',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web de la compañia para mostrar en los documentos'),
        ),
    ]
