# Generated by Django 5.0.2 on 2024-02-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalconfig', '0006_alter_globalconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalconfig',
            options={'default_permissions': (), 'permissions': [('view_global_conf', 'Ver configuración global'), ('change_global_conf', 'Cambiar configuración global'), ('delete_global_conf', 'Borrar configuración global'), ('add_global_conf', 'Agergar configuración global')], 'verbose_name': 'Configuracion global', 'verbose_name_plural': 'Configuraciones Globales'},
        ),
        migrations.AlterModelOptions(
            name='historicalglobalconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Configuracion global', 'verbose_name_plural': 'historical Configuraciones Globales'},
        ),
    ]
